apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
  labels:
    app: kubernetes-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-deployment
  template:
    metadata:
      labels:
        app: kubernetes-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 8080
        env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: secrets
              key: USER_NAME
        - name: password
          valueFrom:
            secretKeyRef:
              name: secrets
              key: USER_PWD
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
spec:
  selector:
    app: kubernetes
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080